[tox]
skipsdist = True

[testenv]
commands =
  {envpython} -m yapf --diff --recursive phile setup.py test_phile
  {envpython} -m mypy --show-error-codes .
  {envpython} -m coverage erase
  {envpython} -m coverage run
  {envpython} -m coverage report
  {envpython} -m docs clean
  {envpython} -m docs html
extras = dev
usedevelop = True
