from typing import Any

def name(item: Any): ...
def is_classmethod(instancemethod: Any, klass: Any): ...
def is_static_method(method: Any, klass: Any): ...
def is_class_private_name(name: Any): ...
def method_name(method: Any): ...
def format_arg_value(arg_val: Any): ...
def echo(fn: Any, write: Any = ...): ...
def echo_instancemethod(klass: Any, method: Any, write: Any = ...) -> None: ...
def echo_class(klass: Any, write: Any = ...) -> None: ...
def echo_module(mod: Any, write: Any = ...) -> None: ...
