from typing import Any
from watchdog.utils import WatchdogShutdown as WatchdogShutdown, load_class as load_class
from watchdog.version import VERSION_STRING as VERSION_STRING

CONFIG_KEY_TRICKS: str
CONFIG_KEY_PYTHON_PATH: str

def path_split(pathname_spec: Any, separator: Any = ...): ...
def add_to_sys_path(pathnames: Any, index: int = ...) -> None: ...
def load_config(tricks_file_pathname: Any): ...
def parse_patterns(patterns_spec: Any, ignore_patterns_spec: Any, separator: str = ...): ...
def observe_with(observer: Any, event_handler: Any, pathnames: Any, recursive: Any) -> None: ...
def schedule_tricks(observer: Any, tricks: Any, pathname: Any, recursive: Any) -> None: ...
def tricks_from(args: Any) -> None: ...
def tricks_generate_yaml(args: Any) -> None: ...
def log(args: Any) -> None: ...
def shell_command(args: Any) -> None: ...
def auto_restart(args: Any) -> None: ...

epilog: str
parser: Any

def main() -> None: ...
