from typing import Any
from watchdog.events import DirCreatedEvent as DirCreatedEvent, DirDeletedEvent as DirDeletedEvent, DirModifiedEvent as DirModifiedEvent, DirMovedEvent as DirMovedEvent, FileCreatedEvent as FileCreatedEvent, FileDeletedEvent as FileDeletedEvent, FileModifiedEvent as FileModifiedEvent, FileMovedEvent as FileMovedEvent
from watchdog.observers.api import BaseObserver as BaseObserver, DEFAULT_EMITTER_TIMEOUT as DEFAULT_EMITTER_TIMEOUT, DEFAULT_OBSERVER_TIMEOUT as DEFAULT_OBSERVER_TIMEOUT, EventEmitter as EventEmitter

class FSEventsEmitter(EventEmitter):
    def __init__(self, event_queue: Any, watch: Any, timeout: Any = ...) -> None: ...
    def on_thread_stop(self) -> None: ...
    def queue_events(self, timeout: Any) -> None: ...
    pathnames: Any = ...
    def run(self) -> None: ...

class FSEventsObserver(BaseObserver):
    def __init__(self, timeout: Any = ...) -> None: ...
    def schedule(self, event_handler: Any, path: Any, recursive: bool = ...): ...
